version: '3.3'

services:
  mysql:
    image: mysql:5.7.21
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
    ports:
      - "3306:3306"