version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
        environment:
          VERSION_PREFIX: "3.1"
      - image: mysql:5.6
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
        environment:
          MYSQL_ROOT_PASSWORD: root-password
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Build
          command: |
            export VERSION="${VERSION_PREFIX}.${CIRCLE_BUILD_NUM}"
            dotnet pack -c Release -o artifacts src/Xunit.Fixture.Mvc.EntityFramework /p:PackageVersion=$VERSION /p:Version=$VERSION /p:AssemblyVersion=$VERSION
      - run:
          name: Integration tests
          command: dotnet test -c Release example/Breakfast.Api.Tests
      - run:
          name: Push NuGet packages
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]
            then
              dotnet nuget push artifacts/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
            fi

workflows:
  version: 2
  build-publish:
    jobs:
      - build:
          context: nuget-push